apiVersion: batch/v1
kind: Job
metadata:
  name: dghz
  labels:
    name: dghz
spec:
  parallelism: 4
  template:
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      containers:
      - name: burster
        image: darktrop/dghz:master
        args: ["--connections 4 --cpus 3 --concurrency ${CONCURRENCY} --rps ${QPS}", "${SERVER_IP}:8080"]
        resources:
          limits:
            cpu: "3"
            memory: 4Gi
          requests:
            cpu: "3"
            memory: 4Gi

      restartPolicy: Never
      hostNetwork: true
