apiVersion: v1
kind: Pod
metadata:
  name: rusthttp
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: rusthttp
    image: darktrop/rust-http:master
    imagePullPolicy: "Always"
    env:
      - name: WORKERS
        value: "${CORE_COUNT}"
    resources:
      limits:
        cpu: "3"
        memory: 4Gi
    ports:
      - name: http
        containerPort: 8080
        protocol: TCP

  restartPolicy: Never
  hostNetwork: true
  dnsPolicy: Default
