apiVersion: v1
kind: Pod
metadata:
  name: burster
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: burster
    image: darktrop/dghz
    resources:
      limits:
        cpu: "4"
        memory: 4Gi
      requests:
        cpu: "3"
        memory: 4Gi
    tty: true
  restartPolicy: Never
  hostNetwork: true
  dnsPolicy: Default
