name: Docker Image CI
on:
  push:
    branches: [ master ]
jobs:
  build_server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd go-grpc && docker build . --tag darktrop/benchmark-grpc:$(date +%s)
    
  build_client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd burster && docker build . --tag darktrop/dghz:$(date +%s)
